{"name": "test_Lambdatest_radio_button_demo_value", "status": "failed", "statusDetails": {"message": "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"test_Lambdatest_radio_button_demo_value\" (test_assertions_soft.AssertionsTest):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"Verify Gender, Title and Age group\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"c:\\Users\\shawn\\OneDrive\\Documents\\Tech\\Python\\VSCode_Testing\\Tests\\DemoPytest\\test_assertions_soft.py\", line 17, in test_Lambdatest_radio_button_demo_value\n  File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 1166, in assertIs\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 715, in fail\n    raise self.failureException(msg)\nAssertionError: 'Male' is not 'Male' : Gender is not correct\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"Verify Gender, Title and Age group\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"c:\\Users\\shawn\\OneDrive\\Documents\\Tech\\Python\\VSCode_Testing\\Tests\\DemoPytest\\test_assertions_soft.py\", line 20, in test_Lambdatest_radio_button_demo_value\n  File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 1152, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 715, in fail\n    raise self.failureException(msg)\nAssertionError: '51' not found in '15 - 50' : Age group is not correct\n\n-+ [2/2] +-", "trace": "self = <test_assertions_soft.AssertionsTest testMethod=test_Lambdatest_radio_button_demo_value>\n\n>   ???\n\nc:\\Users\\shawn\\OneDrive\\Documents\\Tech\\Python\\VSCode_Testing\\Tests\\DemoPytest\\test_assertions_soft.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following 2 failures were found in \"test_Lambdatest_radio_button_demo_value\" (test_assertions_soft.AssertionsTest):\nE   +----------------------+----------------------+----------------------+\nE    Failure 1 (\"Verify Gender, Title and Age group\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"c:\\Users\\shawn\\OneDrive\\Documents\\Tech\\Python\\VSCode_Testing\\Tests\\DemoPytest\\test_assertions_soft.py\", line 17, in test_Lambdatest_radio_button_demo_value\nE     File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 1166, in assertIs\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: 'Male' is not 'Male' : Gender is not correct\nE   \nE   -+ [1/2] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 2 (\"Verify Gender, Title and Age group\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"c:\\Users\\shawn\\OneDrive\\Documents\\Tech\\Python\\VSCode_Testing\\Tests\\DemoPytest\\test_assertions_soft.py\", line 20, in test_Lambdatest_radio_button_demo_value\nE     File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 1152, in assertIn\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"C:\\Users\\shawn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '51' not found in '15 - 50' : Age group is not correct\nE   \nE   -+ [2/2] +-"}, "start": 1742851288686, "stop": 1742851300869, "uuid": "ec3e8ef2-5dd6-4fb3-9017-78a083e1aaf4", "historyId": "4e173f545cf2d2a3607673fb67f8ea77", "testCaseId": "4e173f545cf2d2a3607673fb67f8ea77", "fullName": "QATests.DemoPytest.test_assertions_soft.AssertionsTest#test_Lambdatest_radio_button_demo_value", "labels": [{"name": "parentSuite", "value": "QATests.DemoPytest"}, {"name": "suite", "value": "test_assertions_soft"}, {"name": "subSuite", "value": "AssertionsTest"}, {"name": "host", "value": "ShawnAcer"}, {"name": "thread", "value": "80872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "QATests.DemoPytest.test_assertions_soft"}]}